### ISSUE TITLE
I think this repo has the wrong URL

### ISSUE THREAD

**Issue by christianbundy** [dominictarr/is-cannonical-base64#1]
The npm module (and its `repository` field) point to dominictarr/is-canonical-base64, but this Git repo has an extra `n` in "canonical". Anything I can do to help fix this?

**Comment by dominictarr** [comment]
use https://www.npmjs.com/package/is-canonical-base64 instead, turns out "canonical" is the uh, canonical way to spell "canonical".

**Comment by christianbundy** [comment]
Thanks for the rename!

https://github.com/dominictarr/is-canonical-base64
